### ISSUE TITLE
Ability to check reached goals

### ISSUE THREAD

**Issue by Oscuro87** [Lockyy/Scenario-Generator#4]
It would be cool if we could click on an objective that we consider achieved, making the "block" turns green.

**Comment by Lockyy** [comment]
That's a really good idea, I'll add it to my feature list

**Comment by Lockyy** [comment]
Built and integrated into the site. You can now click on objectives to mark them complete, turning them green.

**Comment by Oscuro87** [comment]
Great! Thanks! :)
